// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA83iizop7-SxxvbeOO_xAp8iiykj6X2E0',
    appId: '1:1077245727083:web:4336344d16e0493b9fbc2e',
    messagingSenderId: '1077245727083',
    projectId: 'today-plan-249cd',
    authDomain: 'today-plan-249cd.firebaseapp.com',
    storageBucket: 'today-plan-249cd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe7xH7yohg-6JDGk2w6aNLdtpESYZsZv4',
    appId: '1:1077245727083:android:70d4d91fc6d89bfe9fbc2e',
    messagingSenderId: '1077245727083',
    projectId: 'today-plan-249cd',
    storageBucket: 'today-plan-249cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiYcoknoF6qirOeQe4nwWDekP2N_v8MQM',
    appId: '1:1077245727083:ios:59e2650869c204e39fbc2e',
    messagingSenderId: '1077245727083',
    projectId: 'today-plan-249cd',
    storageBucket: 'today-plan-249cd.firebasestorage.app',
    iosBundleId: 'com.example.todayPlan',
  );
}
